name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: 
    - main
jobs:
  lint_test_and_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: npm install, lint, test and build
      run: |
        npm install
        npm run lint
        npm run test:coverage
        npm run build
    - if: github.event_name == 'pull_request'
      name: Create github-action report
      uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coverage/lcov.info
    - if: github.event_name == 'push'
      name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
    - if: github.event_name == 'push'
      name: Publish package to github package repository
      run: npm publish
      env: 
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: coverage
